#!/bin/bash

setupJohnny() {
  git clone https://github.com/danielsiwiec/git-kata.git .johnny
  cd .johnny
  git checkout kata1
  cd ..
}

setupJohnny > /dev/null 2>&1

echo "Welcome to Git Katas"
echo ""
echo "To start with the first kata, run ./kata1.sh"
