#!/bin/bash

setupJohnny() {
  mkdir .johnny
  cp -r .git .johnny
  cd .johnny
  git config user.name Johnny
  git config user.email johnny@who.com
  git reset --hard
  cd ..
}

setupJohnny > /dev/null 2>&1

echo "Welcome to Git Katas"
echo ""
echo "To start with the first kata, run ./kata1.sh"
